Repository pagopa/pagopa-gpd-payments, pull requests merged in 2022-12, with the labels that each got.

#12 PAGOPA-347 update sonar github action
  .github/workflows/sonar_analysis.yml
  openapi/openapi.json
Labels: ignore-for-release

#14 helm chart creation for uat and deploy [PAGOPA 351]
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: ignore-for-release, deploy

#15 [PAGOPA-350] feat: Added chart config
  helm/values-dev.yaml
Labels: enhancement, ignore-for-release

#16 [PAGOPA-350] fix: added missing env secret
  helm/values-uat.yaml
Labels: ignore-for-release

#17 [PAGOPA 350] Fix GitHub Action
  .github/workflows/update_infra.yml
  .github/workflows/update_openapi.yml
  openapi/openapi.json
Labels: bug

#20 [PAGOPA-355] Azure DevOps performance test - Pipeline migration
  .devops/performance-test-pipelines.yml
  openapi/openapi.json
  performance-test/README.md
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx.conf
  performance-test/run_performance_test.sh
  performance-test/src/dev.environment.json
  performance-test/src/example.csv
  performance-test/src/grafana.sh
  performance-test/src/payments_demand_notice.js
  performance-test/src/payments_workflow.js
  performance-test/src/payments_workflow.oneshot.js
  performance-test/src/test-types/load.json
  performance-test/src/test-types/spike.json
  performance-test/src/test-types/stress.json
  performance-test/src/uat.environment.json
Labels: ignore-for-release, deploy

#21 Pagopa 354 azure dev ops code review pipeline migration and check
  .devops/code-review-pipelines.yml
  Dockerfile
  docker/config/.env
  docker/docker-compose.yml
  docker/run_docker.sh
  integration-test/run_integration_test.sh
  integration-test/src/config/.env.local
  integration-test/src/step_definitions/support/steps.js
  openapi/openapi.json
Labels: ignore-for-release, deploy

#19 [PAGOPA 353] Azure DevOps deploy pipeline migration and check - Pipeline Migration
  .devops/deploy-pipelines.yml
  .gitignore
  docker/README.md
  docker/config/.env
  docker/docker-compose.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/README.MD
  integration-test/run_integration_test.sh
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.prod
  integration-test/src/config/.env.uat
  openapi/openapi.json
Labels: enhancement
