Repository pagopa/pagopa-gpd-payments, pull requests merged in 2023-09, with the labels that each got.

#55 feat: Update API for EC with multiple brokers [PAGOPA-1140]
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/generate_openapi.sh
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payments/controller/receipt/IPaymentsController.java
  src/main/java/it/gov/pagopa/payments/controller/receipt/impl/PaymentsController.java
  src/main/java/it/gov/pagopa/payments/exception/AppError.java
  src/main/java/it/gov/pagopa/payments/exception/ErrorHandler.java
  src/main/java/it/gov/pagopa/payments/service/PaymentsService.java
  src/test/java/it/gov/pagopa/payments/OpenApiGenerationTest.java
  src/test/java/it/gov/pagopa/payments/api/PaymentsControllerTest.java
  src/test/java/it/gov/pagopa/payments/service/PaymentsServiceTest.java
Labels: size/large, minor

#56 fix: Update PaymentsService UNPROCESSABLE_RECEIPT exception raising [PAGOPA-1238]
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payments/service/PaymentsService.java
Labels: bug, size/small

#57 [PAGOPA-1231] fix: Update PO date conversion
  helm/Chart.yaml
  helm/values-dev.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payments/service/PartnerService.java
  src/main/java/it/gov/pagopa/payments/utils/CommonUtil.java
Labels: bug, size/small

#53 [PAGOPA-1129] test: Update integration test
  .github/workflows/integration_test.yml
  integration-test/src/config/.env.local
  integration-test/src/features/gpd_payments.send_receipt_phase.feature
Labels: ignore-for-release, size/small

#58 fix: Exception thrown in case of conflict PAGOPA-1083
  api-test/Payments.postman_collection.json
  openapi/openapi.json
  src/main/java/it/gov/pagopa/payments/exception/AppError.java
  src/main/java/it/gov/pagopa/payments/service/PartnerService.java
  src/test/java/it/gov/pagopa/payments/service/PartnerServiceTest.java
  src/test/java/it/gov/pagopa/payments/service/PaymentsServiceTest.java
Labels: bug, size/small
