Repository pagopa/pagopa-gpd-payments, pull requests merged in 2023-01, with the labels that each got.

#18 ci: update-infra action [WIP]
  .github/workflows/update_infra.yml
Labels: enhancement

#23 ci: config prod settings PAGOPA-352
  docker/docker-compose.yml
  helm/values-prod.yaml
Labels: enhancement, deploy

#24 Fix operations order in swagger config
  src/main/java/it/gov/pagopa/payments/config/SwaggerConfig.java
Labels: enhancement

#25 refactoring code-review: code review only executed in dev
  .devops/code-review-pipelines.yml
Labels: ignore-for-release

#27 [PAGOPA-343] Fix Test Containers issue
  README.md
Labels: ignore-for-release

#28 refactoring deploy and test pipeline
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  docker/run_docker.sh
  integration-test/run_integration_test.sh
  openapi/openapi.json
Labels: ignore-for-release
