Repository pagopa/pagopa-gpd-payments, pull requests merged in 2023-06, with the labels that each got.

#43 fix: Update integration test payments [PAGOPA-994]
  .github/workflows/integration_test.yml
  helm/values-dev.yaml
  integration-test/src/step_definitions/support/utility/axios_common.js
  integration-test/src/step_definitions/support/utility/request_builders.js
Labels: ignore-for-release, size/small

#45 Debug
  .github/workflows/release_deploy.yml
  helm/Chart.lock
Labels: size/small

#46 Pagopa 960 sviluppo migrazione dati storage to cosmos e applicazione in uat e prod
  .devops/deploy-pipelines.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payments/controller/receipt/IPaymentsController.java
  src/main/java/it/gov/pagopa/payments/controller/receipt/impl/PaymentsController.java
  src/main/java/it/gov/pagopa/payments/exception/AppError.java
  src/main/java/it/gov/pagopa/payments/service/PaymentsService.java
  src/test/java/it/gov/pagopa/payments/api/PaymentsControllerTest.java
  src/test/java/it/gov/pagopa/payments/service/PaymentsServiceTest.java
Labels: bug, size/small

#47 feat: PagoPA-833 v2 integration test
  integration-test/src/features/gpd_payments.get_payment_phase.feature
  integration-test/src/features/gpd_payments.verify_phase.feature
  integration-test/src/step_definitions/support/clients/payments_client.js
  integration-test/src/step_definitions/support/logic/common_logic.js
  integration-test/src/step_definitions/support/logic/gpd_logic.js
  integration-test/src/step_definitions/support/steps.js
  integration-test/src/step_definitions/support/utility/request_builders.js
Labels: size/small
