Repository pagopa/pagopa-gpd-payments, pull requests merged in 2023-03, with the labels that each got.

#29 [PAGOPA-712] Integration test enhancement
  .devops/deploy-pipelines.yml
  helm/values-dev.yaml
  helm/values-uat.yaml
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.uat
  integration-test/src/features/gpd_payments.activate_phase.feature
  integration-test/src/features/gpd_payments.send_receipt_phase.feature
  integration-test/src/features/gpd_payments.verify_phase.feature
  integration-test/src/features/gps_payments.feature
  integration-test/src/step_definitions/support/api_config_client.js
  integration-test/src/step_definitions/support/clients/api_config_client.js
  integration-test/src/step_definitions/support/clients/donation_service_client.js
  integration-test/src/step_definitions/support/clients/gpd_client.js
  integration-test/src/step_definitions/support/clients/gps_client.js
  integration-test/src/step_definitions/support/clients/iuv_generator_client.js
  integration-test/src/step_definitions/support/clients/payments_client.js
  integration-test/src/step_definitions/support/gpd_client.js
  integration-test/src/step_definitions/support/logic/common_logic.js
  integration-test/src/step_definitions/support/logic/gpd_logic.js
  integration-test/src/step_definitions/support/logic/gps_logic.js
  integration-test/src/step_definitions/support/logic/health_checks_logic.js
  integration-test/src/step_definitions/support/payments_client.js
  integration-test/src/step_definitions/support/steps.js
  integration-test/src/step_definitions/support/utility/axios_common.js
  integration-test/src/step_definitions/support/utility/data.js
  integration-test/src/step_definitions/support/utility/helpers.js
  integration-test/src/step_definitions/support/utility/request_builders.js
  openapi/openapi.json
Labels: ignore-for-release

#30 PAGOPA-605 fixing paths
  .devops/deploy-pipelines.yml
  .github/workflows/update_infra.yml
  .github/workflows/update_openapi.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/run_integration_test.sh
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.prod
  integration-test/src/config/.env.uat
  integration-test/src/features/gpd_payments.send_receipt_phase.feature
  integration-test/src/features/gpd_payments.verify_phase.feature
  integration-test/src/features/gps_payments.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/support/clients/payments_client.js
  integration-test/src/step_definitions/support/logic/gpd_logic.js
  integration-test/src/step_definitions/support/utility/request_builders.js
  openapi/openapi.json
  performance-test/src/dev.environment.json
  performance-test/src/uat.environment.json
  pom.xml
  src/main/java/it/gov/pagopa/payments/endpoints/validation/PaymentValidator.java
  src/main/java/it/gov/pagopa/payments/service/PartnerService.java
Labels: bug

#34 fixing null pointer exception
  src/main/java/it/gov/pagopa/payments/service/PartnerService.java
Labels: bug

#33 PAGOPA-778 test: GPD Payments check tuning perf test
  .devops/performance-test-pipelines.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx.conf
  performance-test/run_performance_test.sh
  performance-test/src/environments/dev.environment.json
  performance-test/src/environments/local.environment.json
  performance-test/src/environments/uat.environment.json
  performance-test/src/get_payment_workflow.js
  performance-test/src/modules/data.js
  performance-test/src/modules/helpers.js
  performance-test/src/payments_workflow.js
  performance-test/src/send_rt_workflow.js
  performance-test/src/test-types/constant.json
  performance-test/src/test-types/load.json
  performance-test/src/test-types/smoke.json
  performance-test/src/test-types/spike.json
  performance-test/src/test-types/stress.json
  performance-test/src/verify_payment_workflow.js
  src/main/resources/application.properties
Labels: ignore-for-release, size/large

#35 [PAGOPA-777] fix: opex
  .identity/01_data.tf
  .identity/02_application_action_auth.tf
Labels: bug, size/small

#36 [PAGOPA-839] fix to manage empty field in debtor
  .devops/code-review-pipelines.yml
  src/main/java/it/gov/pagopa/payments/service/PartnerService.java
  src/test/java/it/gov/pagopa/payments/service/PartnerServiceTest.java
  src/test/resources/gpd/getPaymentOptionWithIncompleteAddress.json
Labels: bug
