Repository pagopa/pagopa-gpd-payments, pull requests merged in 2023-11, with the labels that each got.

#70 fix: fixing max number of receipts PAGOPA-1321
  src/main/java/it/gov/pagopa/payments/exception/AppError.java
  src/test/java/it/gov/pagopa/payments/service/PaymentsServiceTest.java
Labels: bug, size/small, patch

#73 [PAGOPA-1320-gpd-payments-analizzare-500] logging
  src/main/java/it/gov/pagopa/payments/endpoints/PartnerEndpoint.java
  src/main/java/it/gov/pagopa/payments/endpoints/validation/SoapFaultDefinitionExceptionResolver.java
  src/main/java/it/gov/pagopa/payments/endpoints/validation/SoapMessageDispatcher.java
  src/main/java/it/gov/pagopa/payments/model/DebtPositionStatus.java
  src/main/java/it/gov/pagopa/payments/model/PaymentOptionStatus.java
  src/main/java/it/gov/pagopa/payments/model/PaymentsModelResponse.java
  src/main/java/it/gov/pagopa/payments/model/PaymentsTransferModelResponse.java
  src/main/java/it/gov/pagopa/payments/service/PartnerService.java
Labels: size/small

#76 [PAGOPA-1352] feat: Update metadata
  src/main/java/it/gov/pagopa/payments/model/PaymentOptionMetadataModel.java
  src/main/java/it/gov/pagopa/payments/model/PaymentOptionModel.java
  src/main/java/it/gov/pagopa/payments/model/PaymentOptionModelResponse.java
  src/main/java/it/gov/pagopa/payments/model/PaymentsModelResponse.java
  src/main/java/it/gov/pagopa/payments/model/PaymentsTransferModelResponse.java
  src/main/java/it/gov/pagopa/payments/model/TransferMetadataModel.java
  src/main/java/it/gov/pagopa/payments/model/TransferModelResponse.java
  src/main/java/it/gov/pagopa/payments/service/PartnerService.java
  src/test/java/it/gov/pagopa/payments/service/PartnerServiceTest.java
  src/test/resources/gpd/getPaymentOption.json
  src/test/resources/gpd/getPaymentOptionWithIncompleteAddress.json
  src/test/resources/gpd/getPaymentOption_PO_UNPAID.json
  src/test/resources/gpd/receiptPaymentOption.json
Labels: size/small

#77 [PAGOPA-1359] fix: Update partially PAID case
  integration-test/src/step_definitions/support/utility/request_builders.js
  src/main/java/it/gov/pagopa/payments/service/PartnerService.java
  src/test/java/it/gov/pagopa/payments/service/PartnerServiceTest.java
  src/test/resources/gpd/getPaymentOptionWithIncompleteAddress.json
  src/test/resources/gpd/getPaymentOption_PO_UNPAID.json
Labels: bug, size/small

#78 [PAGOPA-1359] fix
  src/main/java/it/gov/pagopa/payments/service/PartnerService.java
Labels: size/small

#79 Fix GetPayment XML validation error
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payments/service/PartnerService.java
Labels: bug
