Repository pagopa/pagopa-gpd-payments, pull requests merged in 2024-04, with the labels that each got.

#97 chore: add update debtor py-script [PAGOPA-1650]
  utils/requirements.txt
  utils/update_debtor_dev.py
Labels: ignore-for-release, size/small

#99 fix: [PAGOPA-1680] validate when mandatory field is empty
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payments/utils/Validator.java
Labels: size/small

#100 PAGOPA-1658 new filter and total pages output
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payments/controller/receipt/IPaymentsController.java
  src/main/java/it/gov/pagopa/payments/controller/receipt/impl/PaymentsController.java
  src/main/java/it/gov/pagopa/payments/exception/AppError.java
  src/main/java/it/gov/pagopa/payments/mapper/ConvertTableEntityToReceiptModelResponse.java
  src/main/java/it/gov/pagopa/payments/model/PageInfo.java
  src/main/java/it/gov/pagopa/payments/model/PaymentsResult.java
  src/main/java/it/gov/pagopa/payments/service/PaymentsService.java
  src/main/java/it/gov/pagopa/payments/utils/CommonUtil.java
  src/test/java/it/gov/pagopa/payments/api/PaymentsControllerTest.java
  src/test/java/it/gov/pagopa/payments/service/PaymentsServiceTest.java
Labels: enhancement, size/small

#101 feat: retry configuration [PAGOPA-1694]
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payments/service/GpdClient.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
Labels: size/small
